version: 2.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  publish_npm_lib:
    type: string
    default: "INVALID_PARAM"

##
# Yaml anchors
#
##
anchor_configure_git: &anchor_configure_git
  name: Configure git
  command: |
    git config user.email ${GIT_CI_EMAIL}
    git config user.name ${GIT_CI_USER}

anchor_npm_auth: &anchor_npm_auth
  name: Update NPM registry auth token
  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

##
# Executors
#
# CircleCI Executors
##
executors:
  default-docker:
    working_directory: &workingDirVar /home/circleci/project
    resource_class: medium
    docker:
      - image: cimg/node:18.13

jobs:
  publish-npm-lib:
    executor: default-docker
    parameters:
      package_name:
        type: string
        default: "DEFAULT_PACKAGE_NAME"
    steps:
      - checkout
      - attach_workspace:
          at: *workingDirVar
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          <<: *anchor_configure_git
      - run:
          <<: *anchor_npm_auth
      - run: npm config set registry https://registry.npmjs.org/
      - run:
          name: Publish package
          command: |
            echo "not implemented yet - should publish package: << parameters.package_name >>"

workflows:
  publish-npm-lib:
    when: << pipeline.parameters.publish_npm_lib >>
    jobs:
      - publish-npm-lib:
          context: org-global
          package_name: << pipeline.parameters.publish_npm_lib >>
